let math_c = require('./index.js');
let math_basicMath = new math_c.BasicMath();
let math_functionsMath = new math_c.FunctionsMath();

console.log(math_basicMath.addition(1, 2));
console.log(math_basicMath.addition(1, 2).result);
console.log(math_basicMath.addition(1, 2, 3));
console.log(math_basicMath.addition(1, 2, 3).result);
console.log(math_basicMath.addition([1, 2, 3]));
console.log(math_basicMath.addition([1, 2, 3]).result);
console.log(math_basicMath.subtraction(1, 2));
console.log(math_basicMath.subtraction(1, 2).result);
console.log(math_basicMath.subtraction(1, 2, 3));
console.log(math_basicMath.subtraction(1, 2, 3).result);
console.log(math_basicMath.subtraction([1, 2, 3]));
console.log(math_basicMath.subtraction([1, 2, 3]).result);
console.log(math_basicMath.multiplication(1, 2));
console.log(math_basicMath.multiplication(1, 2).result);
console.log(math_basicMath.multiplication(1, 2, 3));
console.log(math_basicMath.multiplication(1, 2, 3).result);
console.log(math_basicMath.multiplication([1, 2, 3]));
console.log(math_basicMath.multiplication([1, 2, 3]).result);
console.log(math_basicMath.division(1, 2));
console.log(math_basicMath.division(1, 2).result);
console.log(math_basicMath.division(1, 2, 3));
console.log(math_basicMath.division(1, 2, 3).result);
console.log(math_basicMath.division([1, 2, 3]));
console.log(math_basicMath.division([1, 2, 3]).result);
console.log(math_basicMath.division(1, 0));
console.log(math_basicMath.division(1, 0).result);
console.log(math_basicMath.division(1, 0, 3));
console.log(math_basicMath.division(1, 0, 3).result);
console.log(math_basicMath.division([1, 2, 0]));
console.log(math_basicMath.division([1, 2, 0]).result);
console.log(math_basicMath.sinDegrees(-9).result);
console.log(math_basicMath.round(2123456789, -3).result);
